version: '3.9'

# networks
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mailu-default
    ipam:
      driver: default
      config:
        - subnet: 172.25.10.0/24
  radicale:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mailu-radicale
    ipam:
      driver: default
      config:
        - subnet: 172.25.11.0/24
          gateway: 172.25.11.1
  webmail:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mailu-webmail
    ipam:
      driver: default
      config:
        - subnet: 172.25.12.0/24
          gateway: 172.25.12.1
  noinet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mailu-noinet
    ipam:
      driver: default
      config:
        - subnet: 172.25.13.0/24
          gateway: 172.25.13.1
    internal: true

# volumes
volumes:
  redis:
  certs:
  nginx:
  data:
  dkim:
  mail:
  dovecot:
  mailqueue:
  postfix:
  filter:
  rspamd:
  dav:
  fetchmail:
  webmail:
  roundcube:

# services
services:

  # External dependencies
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    volumes:
      - redis:/data
    depends_on:
      - resolver
    dns:
      - 172.25.10.254

  # Core services
  front:
    container_name: front
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master}
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "8187:80"
      - "4445:443"
      - "2525:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "4190:4190"
    networks:
      - default
      - webmail
      - radicale
    volumes:
      - certs:/certs
      - nginx:/overrides:ro
    depends_on:
      - resolver
    dns:
      - 172.25.10.254

  resolver:
    container_name: resolver
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-master}
    env_file: stack.env
    restart: always
    networks:
      default:
        ipv4_address: 172.25.10.254

  admin:
    container_name: admin
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master}
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - data:/data
      - dkim:/dkim
    depends_on:
      - redis
      - resolver
    dns:
      - 172.25.10.254

  imap:
    container_name: imap
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-master}
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - mail:/mail
      - dovecot:/overrides:ro
    depends_on:
      - front
      - resolver
    dns:
      - 172.25.10.254

  smtp:
    container_name: smtp
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-master}
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - mailqueue:/queue
      - postfix:/overrides:ro
    depends_on:
      - front
      - resolver
    dns:
      - 172.25.10.254

  oletools:
    container_name: oletools
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-master}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 172.25.10.254

  antispam:
    container_name: antispam
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-master}
    hostname: antispam
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - filter:/var/lib/rspamd
      - rspamd:/overrides:ro
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 172.25.10.254

  # Optional services
  antivirus:
    container_name: antivirus
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-master}
    restart: always
    env_file: stack.env
    volumes:
      - filter:/data
    depends_on:
      - resolver
    dns:
      - 172.25.10.254

  webdav:
    container_name: webdav
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-master}
    restart: always
    volumes:
      - dav:/data
    networks:
      - radicale

  fetchmail:
    container_name: fetchmail
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-master}
    restart: always
    env_file: stack.env
    volumes:
      - fetchmail:/data
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 172.25.10.254

  # Webmail
  webmail:
    container_name: webmail
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-master}
    restart: always
    env_file: stack.env
    volumes:
      - webmail:/data
      - roundcube:/overrides:ro
    networks:
      - webmail
    depends_on:
      - front
